-- Tipos de ocorrência (estrutura + seed)
create table if not exists public.tipos_ocorrencia (
  id bigint generated by default as identity primary key,
  codigo text,
  descricao text not null,
  ativo boolean not null default true,
  ordem integer not null default 1000,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tipos_ocorrencia_unq on public.tipos_ocorrencia ((coalesce(codigo, '')), descricao);
create index if not exists tipos_ocorrencia_ordem_idx on public.tipos_ocorrencia (ordem);
create index if not exists tipos_ocorrencia_ativo_idx on public.tipos_ocorrencia (ativo);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tipos_ocorrencia_updated_at on public.tipos_ocorrencia;
create trigger trg_tipos_ocorrencia_updated_at
before update on public.tipos_ocorrencia
for each row
execute function public.set_updated_at();

alter table public.tipos_ocorrencia enable row level security;

drop policy if exists tipos_ocorrencia_select_anon on public.tipos_ocorrencia;
create policy tipos_ocorrencia_select_anon
on public.tipos_ocorrencia for select to anon using (true);

drop policy if exists tipos_ocorrencia_write_anon on public.tipos_ocorrencia;
create policy tipos_ocorrencia_write_anon
on public.tipos_ocorrencia for all to anon using (true) with check (true);

insert into public.tipos_ocorrencia (codigo, descricao, ativo, ordem) values
  ('192', 'DANIFICOU OBJETOS E/OU LOCAIS DO COLÉGIO', true, 1),
  ('174', 'APOSTILA INCOMPLETA', true, 2),
  ('9', 'LIÇÃO DE CASA INCOMPLETA', true, 3),
  ('188', 'NÃO COPIOU A LIÇÃO', true, 4),
  ('7', 'NÃO ENTREGOU A ATIVIDADE', true, 5),
  ('12', 'NÃO ENTREGOU A AVALIAÇÃO ASSINADA', true, 6),
  ('6', 'NÃO ENTREGOU O TRABALHO', true, 7),
  ('10', 'NÃO FEZ EXERCÍCIO EM SALA DE AULA', true, 8),
  ('133', 'NÃO PARTICIPA DAS AULAS', true, 9),
  ('8', 'NÃO REALIZOU A LIÇÃO DE CASA', true, 10),
  ('14', 'NÃO TROUXE APOSTILA', true, 11),
  ('11', 'NÃO TROUXE MATERIAL SOLICITADO', true, 12),
  ('13', 'NECESSITA DE AUXÍLIO DURANTE A REALIZAÇÃO DOS EXERCÍCIOS', true, 13),
  ('18', 'AGREDIR FISICAMENTE O COLEGA', true, 14),
  ('16', 'AGREDIR VERBALMENTE O COLEGA', true, 15),
  ('139', 'CHEGADA ATRASADA', true, 16),
  ('19', 'DANIFICAR A MOBÍLIA DA SALA', true, 17),
  ('15', 'DESACATAR O PROFESSOR', true, 18),
  ('141', 'ENTRADA ATRASADA', true, 19),
  ('20', 'IMPEDIU O PROFESSOR DE DAR A AULA', true, 20),
  ('17', 'NÃO RESPEITAR AS REGRAS DO COLÉGIO', true, 21),
  ('137', 'NÃO USOU UNIFORME', true, 22),
  ('21', 'USOU O CELULAR DURANTE A AULA', true, 23)
on conflict ((coalesce(codigo, '')), descricao) do update
set ativo = excluded.ativo,
    ordem = excluded.ordem,
    updated_at = now();
